### PR TITLE
Add ScalaJS support

### PR DESCRIPTION
**Pull request by sirocchj**
Would be nice to fully support Laserdisc on ScalaJS now that FS2 IO module is available :)

### CODE REVIEW

**Comment by sirocchj** [comment]
@barambani when you can

**Comment by sirocchj** [comment]
@barambani what do you think?

**Comment by sirocchj** [comment]
Ping @barambani :)

**Review by barambani — COMMENTED** [review]
💯

**Review by barambani — APPROVED** [review]

**Pull request merged**
