### PR TITLE
Added Layer constructor for Zio. Refactored existing. Added Github Actions for CI

### PR DESCRIPTION
**Pull request by barambani**
Actions for CI

### CODE REVIEW

**Review by sirocchj — APPROVED** [review]
Neat!! Do you still need the travis file I wonder...?

**Comment by sirocchj** [comment]
> Neat!! Do you still need the travis file I wonder...?

Lol just saw you removed it now

**Comment by barambani** [comment]
yes, I broke everything 🤣 . Fixing.

**Review by sirocchj — APPROVED** [review]
Ship it!

**Pull request merged**
